// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeggieSwappyServer.Data;

namespace VeggieSwappyServer.Data.Migrations
{
    [DbContext(typeof(VeggieSwappyServerContext))]
    [Migration("20210601113701_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradeUser", b =>
                {
                    b.Property<int>("TradesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("TradesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TradeUser");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposingUserId")
                        .HasColumnType("int");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.ToTable("CurrentTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.ProposedTradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentTradeProposalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RejectedTradeProposalId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTradeProposalId");

                    b.HasIndex("RejectedTradeProposalId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposingUserId")
                        .HasColumnType("int");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("rejectedTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(4340),
                            ImageUrl = "apples.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(4340),
                            Name = "apples"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5394),
                            ImageUrl = "artichokes.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5394),
                            Name = "artichokes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5408),
                            ImageUrl = "asparagus.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5408),
                            Name = "asparagus"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5411),
                            ImageUrl = "bananas.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5411),
                            Name = "bananas"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5414),
                            ImageUrl = "bell-peppers.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5414),
                            Name = "bell-peppers"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5418),
                            ImageUrl = "blueberries.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5418),
                            Name = "blueberries"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5421),
                            ImageUrl = "bok-choy.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5421),
                            Name = "bok-choy"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5425),
                            ImageUrl = "broccoli.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5425),
                            Name = "broccoli"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5427),
                            ImageUrl = "brussels-sprouts.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5427),
                            Name = "brussels-sprouts"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5430),
                            ImageUrl = "carrots.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5430),
                            Name = "carrots"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5433),
                            ImageUrl = "cherries.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5433),
                            Name = "cherries"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5436),
                            ImageUrl = "chilis.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5436),
                            Name = "chilis"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5439),
                            ImageUrl = "coconuts.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5439),
                            Name = "coconuts"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5442),
                            ImageUrl = "coriander.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5442),
                            Name = "coriander"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5445),
                            ImageUrl = "corn.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5445),
                            Name = "corn"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5448),
                            ImageUrl = "cucumbers.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5448),
                            Name = "cucumbers"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5451),
                            ImageUrl = "dragon-fruits.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5451),
                            Name = "dragon-fruits"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5454),
                            ImageUrl = "durians.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5454),
                            Name = "durians"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5457),
                            ImageUrl = "eggplants.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5457),
                            Name = "eggplants"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5460),
                            ImageUrl = "garlic.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5460),
                            Name = "garlic"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5463),
                            ImageUrl = "grapes.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5463),
                            Name = "grapes"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5466),
                            ImageUrl = "guavas.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5466),
                            Name = "guavas"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5469),
                            ImageUrl = "kiwis.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5469),
                            Name = "kiwis"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5472),
                            ImageUrl = "lemons.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5472),
                            Name = "lemons"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5475),
                            ImageUrl = "mangos.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5475),
                            Name = "mangos"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5478),
                            ImageUrl = "mangosteens.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5478),
                            Name = "mangosteens"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5481),
                            ImageUrl = "melons.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5481),
                            Name = "melons"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5484),
                            ImageUrl = "mushrooms.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5484),
                            Name = "mushrooms"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5487),
                            ImageUrl = "olives.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5487),
                            Name = "olives"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5490),
                            ImageUrl = "oranges.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5490),
                            Name = "oranges"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5492),
                            ImageUrl = "papayas.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5492),
                            Name = "papayas"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5495),
                            ImageUrl = "peaches.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5495),
                            Name = "peaches"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5498),
                            ImageUrl = "pears.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5498),
                            Name = "pears"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5501),
                            ImageUrl = "peas.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5501),
                            Name = "peas"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5504),
                            ImageUrl = "pineapples.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5504),
                            Name = "pineapples"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5507),
                            ImageUrl = "pomegranates.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5507),
                            Name = "pomegranates"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5510),
                            ImageUrl = "potatoes.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5510),
                            Name = "potatoes"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5513),
                            ImageUrl = "pumpkins.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5513),
                            Name = "pumpkins"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5516),
                            ImageUrl = "radish.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5516),
                            Name = "radish"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5519),
                            ImageUrl = "radishes.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5519),
                            Name = "radishes"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5522),
                            ImageUrl = "raspberries.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5522),
                            Name = "raspberries"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5525),
                            ImageUrl = "salad.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5525),
                            Name = "salad"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5528),
                            ImageUrl = "salads.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5528),
                            Name = "salads"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5531),
                            ImageUrl = "scallions.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5531),
                            Name = "scallions"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5534),
                            ImageUrl = "spinach.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5534),
                            Name = "spinach"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5537),
                            ImageUrl = "star-fruits.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5537),
                            Name = "star-fruits"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5540),
                            ImageUrl = "strawberries.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5540),
                            Name = "strawberries"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5543),
                            ImageUrl = "sweet-potatoes.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5543),
                            Name = "sweet-potatoes"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5546),
                            ImageUrl = "tomatoes.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5546),
                            Name = "tomatoes"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5549),
                            ImageUrl = "watermelons.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5549),
                            Name = "watermelons"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5551),
                            ImageUrl = "v-coin.svg",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 999, DateTimeKind.Local).AddTicks(5551),
                            Name = "v-coin"
                        });
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TradeStatus")
                        .HasColumnType("int");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 992, DateTimeKind.Local).AddTicks(1921),
                            Email = "Pieter@mail.com",
                            FirstName = "Pieter",
                            ImageUrl = "https://robohash.org/Pieter",
                            IsAdmin = true,
                            LastName = "Corp",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 992, DateTimeKind.Local).AddTicks(1921),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6188),
                            Email = "Nick@mail.com",
                            FirstName = "Nick",
                            ImageUrl = "https://robohash.org/Nick",
                            IsAdmin = true,
                            LastName = "Vr",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6188),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6486),
                            Email = "Kobe@mail.com",
                            FirstName = "Kobe",
                            ImageUrl = "https://robohash.org/Kobe",
                            IsAdmin = true,
                            LastName = "Delo",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6486),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6514),
                            Email = "Dries@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries",
                            IsAdmin = true,
                            LastName = "Maes",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6514),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6532),
                            Email = "BartjeWevertje@mail.com",
                            FirstName = "BartjeWevertje",
                            ImageUrl = "https://robohash.org/BartjeWevertje",
                            IsAdmin = false,
                            LastName = "Wevertje",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6532),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6547),
                            Email = "Stofzuiger@mail.com",
                            FirstName = "Stofzuiger",
                            ImageUrl = "https://robohash.org/Stofzuiger",
                            IsAdmin = false,
                            LastName = "Zuiger",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6547),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6563),
                            Email = "Dirk@mail.com",
                            FirstName = "Dirk",
                            ImageUrl = "https://robohash.org/Dirk",
                            IsAdmin = false,
                            LastName = "Visser",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6563),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6578),
                            Email = "Andreas@mail.com",
                            FirstName = "Andreas",
                            ImageUrl = "https://robohash.org/Andreas",
                            IsAdmin = false,
                            LastName = "VanGrieken",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6578),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6593),
                            Email = "Mihiel@mail.com",
                            FirstName = "Mihiel",
                            ImageUrl = "https://robohash.org/Mihiel",
                            IsAdmin = false,
                            LastName = "Mihoen",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6593),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6608),
                            Email = "Luc@mail.com",
                            FirstName = "Luc",
                            ImageUrl = "https://robohash.org/Luc",
                            IsAdmin = false,
                            LastName = "DeHaantje",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6608),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6624),
                            Email = "VerhofstadDeZeemlap@europeesemailadres.com",
                            FirstName = "Verhofstad",
                            ImageUrl = "https://robohash.org/Zeemlap",
                            IsAdmin = false,
                            LastName = "Zeemlap",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6624),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6639),
                            Email = "Driesdentweedenmaarnidezelfden@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries2",
                            IsAdmin = false,
                            LastName = "VanKorteNekke",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6639),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6654),
                            Email = "Joyce@mail.com",
                            FirstName = "Joyce",
                            ImageUrl = "https://robohash.org/Tomatenplukker",
                            IsAdmin = false,
                            LastName = "Tomatenplukker",
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 0, 996, DateTimeKind.Local).AddTicks(6654),
                            PasswordHash = new byte[] { 17, 72, 45, 198, 174, 228, 60, 186, 36, 68, 62, 156, 160, 98, 222, 2, 150, 38, 125, 2, 44, 224, 244, 108, 110, 96, 109, 252, 33, 106, 169, 95, 176, 67, 5, 203, 67, 190, 208, 49, 110, 222, 57, 2, 19, 222, 91, 222, 24, 20, 14, 29, 229, 242, 171, 208, 132, 233, 52, 58, 229, 42, 129, 120 },
                            PasswordSalt = new byte[] { 23, 200, 236, 205, 44, 102, 98, 18, 200, 126, 167, 202, 90, 222, 11, 183, 205, 196, 65, 242, 193, 23, 193, 68, 42, 201, 44, 28, 160, 107, 72, 1, 131, 5, 224, 152, 208, 3, 85, 234, 241, 235, 57, 96, 254, 180, 101, 111, 249, 212, 25, 195, 236, 14, 176, 193, 67, 229, 53, 147, 164, 14, 100, 245, 111, 116, 182, 10, 25, 224, 172, 107, 83, 17, 44, 131, 5, 243, 242, 152, 163, 142, 183, 113, 126, 166, 88, 165, 98, 104, 119, 47, 240, 1, 18, 36, 13, 115, 27, 221, 3, 78, 133, 188, 55, 13, 248, 236, 211, 77, 35, 148, 127, 253, 28, 142, 141, 2, 229, 204, 243, 224, 17, 244, 166, 67, 108, 254 }
                        });
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.UserTradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTradeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(6137),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(6137),
                            ResourceId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7627),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7627),
                            ResourceId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7642),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7642),
                            ResourceId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7645),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7645),
                            ResourceId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7648),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7648),
                            ResourceId = 11,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7652),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7652),
                            ResourceId = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7655),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7655),
                            ResourceId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7658),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7658),
                            ResourceId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7661),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7661),
                            ResourceId = 7,
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7664),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7664),
                            ResourceId = 20,
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7667),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7667),
                            ResourceId = 21,
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7670),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7670),
                            ResourceId = 22,
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7673),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7673),
                            ResourceId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 14,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7676),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7676),
                            ResourceId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7679),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7679),
                            ResourceId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 16,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7682),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7682),
                            ResourceId = 10,
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7684),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7684),
                            ResourceId = 11,
                            UserId = 6
                        },
                        new
                        {
                            Id = 18,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7687),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7687),
                            ResourceId = 12,
                            UserId = 6
                        },
                        new
                        {
                            Id = 19,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7690),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7690),
                            ResourceId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 20,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7693),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7693),
                            ResourceId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 21,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7697),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7697),
                            ResourceId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 22,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7700),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7700),
                            ResourceId = 20,
                            UserId = 8
                        },
                        new
                        {
                            Id = 23,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7703),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7703),
                            ResourceId = 21,
                            UserId = 8
                        },
                        new
                        {
                            Id = 24,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7706),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7706),
                            ResourceId = 11,
                            UserId = 9
                        },
                        new
                        {
                            Id = 25,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7709),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7709),
                            ResourceId = 12,
                            UserId = 9
                        },
                        new
                        {
                            Id = 26,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7712),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7712),
                            ResourceId = 10,
                            UserId = 9
                        },
                        new
                        {
                            Id = 27,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7715),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7715),
                            ResourceId = 35,
                            UserId = 10
                        },
                        new
                        {
                            Id = 28,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7718),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7718),
                            ResourceId = 37,
                            UserId = 10
                        },
                        new
                        {
                            Id = 29,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7721),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7721),
                            ResourceId = 30,
                            UserId = 10
                        },
                        new
                        {
                            Id = 30,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7724),
                            ModifiedAt = new DateTime(2021, 6, 1, 13, 37, 1, 0, DateTimeKind.Local).AddTicks(7724),
                            ResourceId = 31,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("TradeUser", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", null)
                        .WithMany()
                        .HasForeignKey("TradesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", "Trade")
                        .WithOne("CurrentTradeProposal")
                        .HasForeignKey("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.ProposedTradeItem", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", "CurrentTradeProposal")
                        .WithMany("ProposedTradeItems")
                        .HasForeignKey("CurrentTradeProposalId");

                    b.HasOne("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", "RejectedTradeProposal")
                        .WithMany("ProposedTradeItems")
                        .HasForeignKey("RejectedTradeProposalId");

                    b.HasOne("VeggieSwappyServer.Data.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTradeProposal");

                    b.Navigation("RejectedTradeProposal");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", "Trade")
                        .WithMany("RejectedTradeProposals")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.UserTradeItem", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Resource", "Resource")
                        .WithMany("UserTradeItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", "User")
                        .WithMany("UserTradeItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.Navigation("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.Navigation("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Resource", b =>
                {
                    b.Navigation("UserTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Trade", b =>
                {
                    b.Navigation("CurrentTradeProposal");

                    b.Navigation("RejectedTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.User", b =>
                {
                    b.Navigation("UserTradeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
