// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeggieSwappyServer.Data;

namespace VeggieSwappyServer.Data.Migrations
{
    [DbContext(typeof(VeggieSwappyServerContext))]
    [Migration("20210531190627_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradeUser", b =>
                {
                    b.Property<int>("TradesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("TradesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TradeUser");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposingUserId")
                        .HasColumnType("int");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.ToTable("CurrentTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.ProposedTradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentTradeProposalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RejectedTradeProposalId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTradeProposalId");

                    b.HasIndex("RejectedTradeProposalId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposingUserId")
                        .HasColumnType("int");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("rejectedTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(6833),
                            ImageUrl = "apples.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(6833),
                            Name = "apples"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7904),
                            ImageUrl = "artichokes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7904),
                            Name = "artichokes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7918),
                            ImageUrl = "asparagus.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7918),
                            Name = "asparagus"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7922),
                            ImageUrl = "bananas.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7922),
                            Name = "bananas"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7926),
                            ImageUrl = "bell-peppers.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7926),
                            Name = "bell-peppers"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7928),
                            ImageUrl = "blueberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7928),
                            Name = "blueberries"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7931),
                            ImageUrl = "bok-choy.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7931),
                            Name = "bok-choy"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7934),
                            ImageUrl = "broccoli.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7934),
                            Name = "broccoli"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7937),
                            ImageUrl = "brussels-sprouts.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7937),
                            Name = "brussels-sprouts"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7940),
                            ImageUrl = "carrots.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7940),
                            Name = "carrots"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7942),
                            ImageUrl = "cherries.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7942),
                            Name = "cherries"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7946),
                            ImageUrl = "chilis.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7946),
                            Name = "chilis"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7948),
                            ImageUrl = "coconuts.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7948),
                            Name = "coconuts"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7951),
                            ImageUrl = "coriander.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7951),
                            Name = "coriander"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7954),
                            ImageUrl = "corn.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7954),
                            Name = "corn"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7956),
                            ImageUrl = "cucumbers.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7956),
                            Name = "cucumbers"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7959),
                            ImageUrl = "dragon-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7959),
                            Name = "dragon-fruits"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7962),
                            ImageUrl = "durians.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7962),
                            Name = "durians"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7965),
                            ImageUrl = "eggplants.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7965),
                            Name = "eggplants"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7968),
                            ImageUrl = "garlic.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7968),
                            Name = "garlic"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7970),
                            ImageUrl = "grapes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7970),
                            Name = "grapes"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7973),
                            ImageUrl = "guavas.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7973),
                            Name = "guavas"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7976),
                            ImageUrl = "kiwis.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7976),
                            Name = "kiwis"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7979),
                            ImageUrl = "lemons.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7979),
                            Name = "lemons"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7982),
                            ImageUrl = "mangos.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7982),
                            Name = "mangos"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7984),
                            ImageUrl = "mangosteens.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7984),
                            Name = "mangosteens"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7987),
                            ImageUrl = "melons.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7987),
                            Name = "melons"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7990),
                            ImageUrl = "mushrooms.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7990),
                            Name = "mushrooms"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7993),
                            ImageUrl = "olives.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7993),
                            Name = "olives"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7995),
                            ImageUrl = "oranges.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7995),
                            Name = "oranges"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7998),
                            ImageUrl = "papayas.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(7998),
                            Name = "papayas"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8001),
                            ImageUrl = "peaches.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8001),
                            Name = "peaches"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8004),
                            ImageUrl = "pears.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8004),
                            Name = "pears"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8007),
                            ImageUrl = "peas.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8007),
                            Name = "peas"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8009),
                            ImageUrl = "pineapples.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8009),
                            Name = "pineapples"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8012),
                            ImageUrl = "pomegranates.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8012),
                            Name = "pomegranates"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8015),
                            ImageUrl = "potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8015),
                            Name = "potatoes"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8100),
                            ImageUrl = "pumpkins.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8100),
                            Name = "pumpkins"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8105),
                            ImageUrl = "radish.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8105),
                            Name = "radish"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8108),
                            ImageUrl = "radishes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8108),
                            Name = "radishes"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8111),
                            ImageUrl = "raspberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8111),
                            Name = "raspberries"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8114),
                            ImageUrl = "salad.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8114),
                            Name = "salad"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8117),
                            ImageUrl = "salads.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8117),
                            Name = "salads"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8120),
                            ImageUrl = "scallions.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8120),
                            Name = "scallions"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8122),
                            ImageUrl = "spinach.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8122),
                            Name = "spinach"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8125),
                            ImageUrl = "star-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8125),
                            Name = "star-fruits"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8128),
                            ImageUrl = "strawberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8128),
                            Name = "strawberries"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8130),
                            ImageUrl = "sweet-potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8130),
                            Name = "sweet-potatoes"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8133),
                            ImageUrl = "tomatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8133),
                            Name = "tomatoes"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8136),
                            ImageUrl = "watermelons.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8136),
                            Name = "watermelons"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8139),
                            ImageUrl = "v-coin.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 483, DateTimeKind.Local).AddTicks(8139),
                            Name = "v-coin"
                        });
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 477, DateTimeKind.Local).AddTicks(6288),
                            Email = "Pieter@mail.com",
                            FirstName = "Pieter",
                            ImageUrl = "https://robohash.org/Pieter",
                            IsAdmin = true,
                            LastName = "Corp",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 477, DateTimeKind.Local).AddTicks(6288),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1547),
                            Email = "Nick@mail.com",
                            FirstName = "Nick",
                            ImageUrl = "https://robohash.org/Nick",
                            IsAdmin = true,
                            LastName = "Vr",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1547),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1754),
                            Email = "Kobe@mail.com",
                            FirstName = "Kobe",
                            ImageUrl = "https://robohash.org/Kobe",
                            IsAdmin = true,
                            LastName = "Delo",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1754),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1779),
                            Email = "Dries@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries",
                            IsAdmin = true,
                            LastName = "Maes",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1779),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1795),
                            Email = "BartjeWevertje@mail.com",
                            FirstName = "BartjeWevertje",
                            ImageUrl = "https://robohash.org/BartjeWevertje",
                            IsAdmin = false,
                            LastName = "Wevertje",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1795),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1812),
                            Email = "Stofzuiger@mail.com",
                            FirstName = "Stofzuiger",
                            ImageUrl = "https://robohash.org/Stofzuiger",
                            IsAdmin = false,
                            LastName = "Zuiger",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1812),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1827),
                            Email = "Dirk@mail.com",
                            FirstName = "Dirk",
                            ImageUrl = "https://robohash.org/Dirk",
                            IsAdmin = false,
                            LastName = "Visser",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1827),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1843),
                            Email = "Andreas@mail.com",
                            FirstName = "Andreas",
                            ImageUrl = "https://robohash.org/Andreas",
                            IsAdmin = false,
                            LastName = "VanGrieken",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1843),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1858),
                            Email = "Mihiel@mail.com",
                            FirstName = "Mihiel",
                            ImageUrl = "https://robohash.org/Mihiel",
                            IsAdmin = false,
                            LastName = "Mihoen",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1858),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1874),
                            Email = "Luc@mail.com",
                            FirstName = "Luc",
                            ImageUrl = "https://robohash.org/Luc",
                            IsAdmin = false,
                            LastName = "DeHaantje",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1874),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1889),
                            Email = "VerhofstadDeZeemlap@europeesemailadres.com",
                            FirstName = "Verhofstad",
                            ImageUrl = "https://robohash.org/Zeemlap",
                            IsAdmin = false,
                            LastName = "Zeemlap",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1889),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1905),
                            Email = "Driesdentweedenmaarnidezelfden@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries2",
                            IsAdmin = false,
                            LastName = "VanKorteNekke",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1905),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1920),
                            Email = "Joyce@mail.com",
                            FirstName = "Joyce",
                            ImageUrl = "https://robohash.org/Tomatenplukker",
                            IsAdmin = false,
                            LastName = "Tomatenplukker",
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 481, DateTimeKind.Local).AddTicks(1920),
                            PasswordHash = new byte[] { 130, 199, 110, 225, 152, 155, 218, 162, 74, 234, 130, 232, 235, 150, 45, 187, 187, 45, 169, 99, 48, 86, 97, 118, 245, 176, 73, 17, 228, 16, 52, 247, 200, 188, 248, 154, 163, 55, 210, 226, 91, 32, 130, 33, 102, 224, 184, 233, 222, 221, 33, 106, 169, 213, 24, 151, 64, 46, 194, 157, 37, 254, 202, 27 },
                            PasswordSalt = new byte[] { 142, 119, 216, 176, 76, 88, 189, 201, 36, 78, 40, 136, 151, 23, 95, 23, 2, 5, 76, 40, 185, 233, 207, 104, 89, 46, 23, 64, 90, 208, 32, 1, 103, 62, 77, 250, 185, 101, 51, 178, 70, 168, 171, 12, 50, 33, 151, 145, 126, 220, 108, 150, 101, 99, 148, 103, 14, 6, 124, 34, 171, 58, 193, 48, 110, 19, 168, 4, 154, 92, 43, 44, 240, 14, 43, 24, 83, 76, 196, 36, 9, 146, 2, 213, 254, 31, 0, 129, 12, 152, 226, 105, 48, 219, 239, 32, 19, 72, 255, 69, 209, 131, 139, 111, 2, 240, 64, 127, 164, 228, 12, 133, 207, 167, 248, 202, 179, 183, 26, 32, 224, 187, 53, 131, 96, 19, 136, 134 }
                        });
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.UserTradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTradeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(4488),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(4488),
                            ResourceId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5940),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5940),
                            ResourceId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5953),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5953),
                            ResourceId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5956),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5956),
                            ResourceId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5959),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5959),
                            ResourceId = 11,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5962),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5962),
                            ResourceId = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5965),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5965),
                            ResourceId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5968),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5968),
                            ResourceId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5971),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5971),
                            ResourceId = 7,
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5974),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5974),
                            ResourceId = 20,
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5977),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5977),
                            ResourceId = 21,
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5980),
                            ModifiedAt = new DateTime(2021, 5, 31, 21, 6, 27, 484, DateTimeKind.Local).AddTicks(5980),
                            ResourceId = 22,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("TradeUser", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", null)
                        .WithMany()
                        .HasForeignKey("TradesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", "Trade")
                        .WithOne("CurrentTradeProposal")
                        .HasForeignKey("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.ProposedTradeItem", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", "CurrentTradeProposal")
                        .WithMany("ProposedTradeItems")
                        .HasForeignKey("CurrentTradeProposalId");

                    b.HasOne("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", "RejectedTradeProposal")
                        .WithMany("ProposedTradeItems")
                        .HasForeignKey("RejectedTradeProposalId");

                    b.HasOne("VeggieSwappyServer.Data.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTradeProposal");

                    b.Navigation("RejectedTradeProposal");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", "Trade")
                        .WithMany("RejectedTradeProposals")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.UserTradeItem", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Resource", "Resource")
                        .WithMany("UserTradeItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", "User")
                        .WithMany("UserTradeItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.Navigation("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.Navigation("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Resource", b =>
                {
                    b.Navigation("UserTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Trade", b =>
                {
                    b.Navigation("CurrentTradeProposal");

                    b.Navigation("RejectedTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.User", b =>
                {
                    b.Navigation("UserTradeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
