// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeggieSwappyServer.Data;

namespace VeggieSwappyServer.Data.Migrations
{
    [DbContext(typeof(VeggieSwappyServerContext))]
    [Migration("20210531164355_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradeUser", b =>
                {
                    b.Property<int>("TradesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("TradesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TradeUser");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposingUserId")
                        .HasColumnType("int");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.ToTable("CurrentTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.ProposedTradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentTradeProposalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RejectedTradeProposalId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTradeProposalId");

                    b.HasIndex("RejectedTradeProposalId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposingUserId")
                        .HasColumnType("int");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("rejectedTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(1586),
                            ImageUrl = "apples.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(1586),
                            Name = "apples"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2678),
                            ImageUrl = "artichokes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2678),
                            Name = "artichokes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2692),
                            ImageUrl = "asparagus.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2692),
                            Name = "asparagus"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2695),
                            ImageUrl = "bananas.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2695),
                            Name = "bananas"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2699),
                            ImageUrl = "bell-peppers.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2699),
                            Name = "bell-peppers"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2702),
                            ImageUrl = "blueberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2702),
                            Name = "blueberries"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2705),
                            ImageUrl = "bok-choy.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2705),
                            Name = "bok-choy"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2708),
                            ImageUrl = "broccoli.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2708),
                            Name = "broccoli"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2711),
                            ImageUrl = "brussels-sprouts.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2711),
                            Name = "brussels-sprouts"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2714),
                            ImageUrl = "carrots.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2714),
                            Name = "carrots"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2717),
                            ImageUrl = "cherries.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2717),
                            Name = "cherries"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2719),
                            ImageUrl = "chilis.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2719),
                            Name = "chilis"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2722),
                            ImageUrl = "coconuts.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2722),
                            Name = "coconuts"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2725),
                            ImageUrl = "coriander.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2725),
                            Name = "coriander"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2728),
                            ImageUrl = "corn.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2728),
                            Name = "corn"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2731),
                            ImageUrl = "cucumbers.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2731),
                            Name = "cucumbers"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2733),
                            ImageUrl = "dragon-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2733),
                            Name = "dragon-fruits"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2736),
                            ImageUrl = "durians.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2736),
                            Name = "durians"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2739),
                            ImageUrl = "eggplants.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2739),
                            Name = "eggplants"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2742),
                            ImageUrl = "garlic.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2742),
                            Name = "garlic"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2745),
                            ImageUrl = "grapes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2745),
                            Name = "grapes"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2748),
                            ImageUrl = "guavas.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2748),
                            Name = "guavas"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2750),
                            ImageUrl = "kiwis.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2750),
                            Name = "kiwis"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2753),
                            ImageUrl = "lemons.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2753),
                            Name = "lemons"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2756),
                            ImageUrl = "mangos.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2756),
                            Name = "mangos"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2759),
                            ImageUrl = "mangosteens.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2759),
                            Name = "mangosteens"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2761),
                            ImageUrl = "melons.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2761),
                            Name = "melons"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2764),
                            ImageUrl = "mushrooms.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2764),
                            Name = "mushrooms"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2767),
                            ImageUrl = "olives.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2767),
                            Name = "olives"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2770),
                            ImageUrl = "oranges.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2770),
                            Name = "oranges"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2772),
                            ImageUrl = "papayas.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2772),
                            Name = "papayas"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2775),
                            ImageUrl = "peaches.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2775),
                            Name = "peaches"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2778),
                            ImageUrl = "pears.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2778),
                            Name = "pears"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2781),
                            ImageUrl = "peas.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2781),
                            Name = "peas"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2783),
                            ImageUrl = "pineapples.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2783),
                            Name = "pineapples"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2786),
                            ImageUrl = "pomegranates.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2786),
                            Name = "pomegranates"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2789),
                            ImageUrl = "potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2789),
                            Name = "potatoes"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2792),
                            ImageUrl = "pumpkins.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2792),
                            Name = "pumpkins"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2795),
                            ImageUrl = "radish.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2795),
                            Name = "radish"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2797),
                            ImageUrl = "radishes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2797),
                            Name = "radishes"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2800),
                            ImageUrl = "raspberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2800),
                            Name = "raspberries"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2803),
                            ImageUrl = "salad.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2803),
                            Name = "salad"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2806),
                            ImageUrl = "salads.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2806),
                            Name = "salads"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2808),
                            ImageUrl = "scallions.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2808),
                            Name = "scallions"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2811),
                            ImageUrl = "spinach.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2811),
                            Name = "spinach"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2814),
                            ImageUrl = "star-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2814),
                            Name = "star-fruits"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2817),
                            ImageUrl = "strawberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2817),
                            Name = "strawberries"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2820),
                            ImageUrl = "sweet-potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2820),
                            Name = "sweet-potatoes"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2822),
                            ImageUrl = "tomatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2822),
                            Name = "tomatoes"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2825),
                            ImageUrl = "watermelons.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2825),
                            Name = "watermelons"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2828),
                            ImageUrl = "v-coin.svg",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 97, DateTimeKind.Local).AddTicks(2828),
                            Name = "v-coin"
                        });
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 91, DateTimeKind.Local).AddTicks(2090),
                            Email = "Pieter@mail.com",
                            FirstName = "Pieter",
                            ImageUrl = "https://robohash.org/Pieter",
                            IsAdmin = true,
                            LastName = "Corp",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 91, DateTimeKind.Local).AddTicks(2090),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(5826),
                            Email = "Nick@mail.com",
                            FirstName = "Nick",
                            ImageUrl = "https://robohash.org/Nick",
                            IsAdmin = true,
                            LastName = "Vr",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(5826),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6021),
                            Email = "Kobe@mail.com",
                            FirstName = "Kobe",
                            ImageUrl = "https://robohash.org/Kobe",
                            IsAdmin = true,
                            LastName = "Delo",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6021),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6049),
                            Email = "Dries@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries",
                            IsAdmin = true,
                            LastName = "Maes",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6049),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6241),
                            Email = "BartjeWevertje@mail.com",
                            FirstName = "BartjeWevertje",
                            ImageUrl = "https://robohash.org/BartjeWevertje",
                            IsAdmin = false,
                            LastName = "Wevertje",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6241),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6259),
                            Email = "Stofzuiger@mail.com",
                            FirstName = "Stofzuiger",
                            ImageUrl = "https://robohash.org/Stofzuiger",
                            IsAdmin = false,
                            LastName = "Zuiger",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6259),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6275),
                            Email = "Dirk@mail.com",
                            FirstName = "Dirk",
                            ImageUrl = "https://robohash.org/Dirk",
                            IsAdmin = false,
                            LastName = "Visser",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6275),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6291),
                            Email = "Andreas@mail.com",
                            FirstName = "Andreas",
                            ImageUrl = "https://robohash.org/Andreas",
                            IsAdmin = false,
                            LastName = "VanGrieken",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6291),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6306),
                            Email = "Mihiel@mail.com",
                            FirstName = "Mihiel",
                            ImageUrl = "https://robohash.org/Mihiel",
                            IsAdmin = false,
                            LastName = "Mihoen",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6306),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6323),
                            Email = "Luc@mail.com",
                            FirstName = "Luc",
                            ImageUrl = "https://robohash.org/Luc",
                            IsAdmin = false,
                            LastName = "DeHaantje",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6323),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6338),
                            Email = "VerhofstadDeZeemlap@europeesemailadres.com",
                            FirstName = "Verhofstad",
                            ImageUrl = "https://robohash.org/Zeemlap",
                            IsAdmin = false,
                            LastName = "Zeemlap",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6338),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6353),
                            Email = "Driesdentweedenmaarnidezelfden@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries2",
                            IsAdmin = false,
                            LastName = "VanKorteNekke",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6353),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6369),
                            Email = "Joyce@mail.com",
                            FirstName = "Joyce",
                            ImageUrl = "https://robohash.org/Tomatenplukker",
                            IsAdmin = false,
                            LastName = "Tomatenplukker",
                            ModifiedAt = new DateTime(2021, 5, 31, 18, 43, 55, 94, DateTimeKind.Local).AddTicks(6369),
                            PasswordHash = new byte[] { 144, 216, 148, 59, 213, 91, 155, 116, 170, 234, 13, 188, 82, 5, 31, 15, 192, 213, 77, 4, 61, 148, 224, 212, 88, 156, 200, 164, 110, 47, 66, 164, 147, 50, 217, 65, 242, 207, 162, 175, 246, 7, 116, 239, 91, 47, 119, 238, 7, 141, 188, 102, 60, 248, 76, 237, 19, 92, 49, 68, 169, 207, 36, 48 },
                            PasswordSalt = new byte[] { 208, 218, 61, 247, 228, 43, 101, 62, 96, 43, 93, 64, 102, 248, 16, 171, 146, 10, 51, 252, 219, 189, 108, 99, 18, 143, 144, 136, 229, 155, 45, 133, 161, 44, 14, 239, 88, 62, 183, 255, 14, 31, 13, 127, 111, 57, 5, 20, 118, 16, 37, 164, 222, 254, 113, 187, 174, 199, 94, 190, 117, 123, 235, 234, 79, 235, 11, 168, 90, 70, 136, 240, 125, 223, 51, 93, 249, 63, 130, 17, 222, 156, 143, 95, 125, 183, 45, 189, 202, 192, 144, 172, 253, 91, 181, 77, 78, 241, 159, 179, 95, 57, 133, 189, 225, 136, 54, 115, 216, 79, 76, 98, 3, 50, 170, 158, 197, 2, 34, 123, 56, 135, 171, 220, 149, 120, 158, 21 }
                        });
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.UserTradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTradeItems");
                });

            modelBuilder.Entity("TradeUser", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", null)
                        .WithMany()
                        .HasForeignKey("TradesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", "Trade")
                        .WithOne("CurrentTradeProposal")
                        .HasForeignKey("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.ProposedTradeItem", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", "CurrentTradeProposal")
                        .WithMany("ProposedTradeItems")
                        .HasForeignKey("CurrentTradeProposalId");

                    b.HasOne("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", "RejectedTradeProposal")
                        .WithMany("ProposedTradeItems")
                        .HasForeignKey("RejectedTradeProposalId");

                    b.HasOne("VeggieSwappyServer.Data.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTradeProposal");

                    b.Navigation("RejectedTradeProposal");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Trade", "Trade")
                        .WithMany("RejectedTradeProposals")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.UserTradeItem", b =>
                {
                    b.HasOne("VeggieSwappyServer.Data.Entities.Resource", "Resource")
                        .WithMany("UserTradeItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwappyServer.Data.Entities.User", "User")
                        .WithMany("UserTradeItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.CurrentTradeProposal", b =>
                {
                    b.Navigation("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.RejectedTradeProposal", b =>
                {
                    b.Navigation("ProposedTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Resource", b =>
                {
                    b.Navigation("UserTradeItems");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.Trade", b =>
                {
                    b.Navigation("CurrentTradeProposal");

                    b.Navigation("RejectedTradeProposals");
                });

            modelBuilder.Entity("VeggieSwappyServer.Data.Entities.User", b =>
                {
                    b.Navigation("UserTradeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
